services:
  demo-1:
    public: true
    image: drakkarsoftware/octobot:stable
    replicas: 1
    ports:
      - 5001
    resources:
      cpu: 1
      memory: 3Gi
      storage: 1Gi
    volumes:
      - /octobot/user
      - /octobot/tentacles
  demo-2:
    public: true
    image: drakkarsoftware/octobot:stable
    replicas: 1
    ports:
      - 5001
    resources:
      cpu: 1
      memory: 3Gi
      storage: 1Gi
    volumes:
      - /octobot/user
      - /octobot/tentacles
