name: OctoBot-Demo-Cron
on:
  push:
    branches:
      - '*'
      
jobs:
  demo-redeploy:
    name: OctoBot Demo redeploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Destroy old demo stack"
        uses: okteto/destroy-stack@master
        with:
          namespace: octobot-jlopezbarb
          name: "demo"

      - name: "Deploy new demo stack"
        uses: okteto/deploy-stack@master
        with:
          namespace: octobot-jlopezbarb
          build: "false"
          name: "demo"
